### ISSUE TITLE
Analyze commits failing on a null

### ISSUE THREAD

**Issue by jameswlane** [semantic-release/commit-analyzer#111]
Semantic Release started failing on CircleCI, trying to figure out if its something due to running the beta versions of plugins or something wrong in my pipeline.

Version:
```
    "semantic-release": "16.0.0-beta.17",
    "@semantic-release/changelog": "3.0.2",
    "@semantic-release/commit-analyzer": "7.0.0-beta.1",
    "@semantic-release/github": "5.3.0-beta.7",
    "@semantic-release/npm": "5.2.0-beta.5",
    "@semantic-release/release-notes-generator": "7.1.4",
```

This is the error I am getting:

```
#!/bin/bash -eo pipefail
npm run semantic-release


> status-board@0.0.0-development semantic-release /home/circleci/project/status-board
> semantic-release

[04:34:41] [semantic-release] › ℹ  Running semantic-release version 16.0.0-beta.17
[04:34:41] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[04:34:41] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[04:34:41] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[04:34:41] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[04:34:41] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[04:34:41] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[04:34:41] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[04:34:41] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[04:34:41] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[04:34:41] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[04:34:41] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[04:34:50] [semantic-release] › ✔  Run automated release from branch master
[04:34:55] [semantic-release] › ✔  Allowed to push to the Git repository
[04:34:55] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[04:34:55] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[04:34:55] [semantic-release] [@semantic-release/npm] › ℹ  Wrote NPM_TOKEN to /home/circleci/project/status-board/.npmrc
[04:34:56] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[04:34:56] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[04:34:56] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[04:34:56] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[04:34:56] [semantic-release] › ℹ  Found git tag v1.1.47 associated with version 1.1.47 on branch master
[04:34:56] [semantic-release] › ℹ  Found 19 commits since last release
[04:34:56] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[04:34:56] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(package): Updated packages
[04:34:56] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[04:34:56] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(package): Updated packages
[04:34:56] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[04:34:56] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #368 from jameswlane/renovate/master-jest-23.3.x

chore(deps): update dependency @types/jest to v23.3.13 (master)
[04:34:56] [semantic-release] › ✖  Failed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[04:34:56] [semantic-release] › ✖  An error occurred while running semantic-release: { TypeError: expected a string: "null"
    at Function.micromatch.isMatch (/home/circleci/project/status-board/node_modules/micromatch/index.js:156:11)
    at isMatchWith (/home/circleci/project/status-board/node_modules/@semantic-release/commit-analyzer/lib/analyze-commit.js:25:77)
    at baseIsMatch (/home/circleci/project/status-board/node_modules/lodash/lodash.js:3394:26)
    at isMatchWith (/home/circleci/project/status-board/node_modules/lodash/lodash.js:11862:14)
    at releaseRules.filter (/home/circleci/project/status-board/node_modules/@semantic-release/commit-analyzer/lib/analyze-commit.js:25:9)
    at Array.filter (<anonymous>)
    at module.exports (/home/circleci/project/status-board/node_modules/@semantic-release/commit-analyzer/lib/analyze-commit.js:18:6)
    at filter.every (/home/circleci/project/status-board/node_modules/@semantic-release/commit-analyzer/index.js:48:27)
    at Array.every (<anonymous>)
    at analyzeCommits (/home/circleci/project/status-board/node_modules/@semantic-release/commit-analyzer/index.js:33:5) pluginName: '@semantic-release/commit-analyzer' }
{ TypeError: expected a string: "null"
    at Function.micromatch.isMatch (/home/circleci/project/status-board/node_modules/micromatch/index.js:156:11)
    at isMatchWith (/home/circleci/project/status-board/node_modules/@semantic-release/commit-analyzer/lib/analyze-commit.js:25:77)
    at baseIsMatch (/home/circleci/project/status-board/node_modules/lodash/lodash.js:3394:26)
    at isMatchWith (/home/circleci/project/status-board/node_modules/lodash/lodash.js:11862:14)
    at releaseRules.filter (/home/circleci/project/status-board/node_modules/@semantic-release/commit-analyzer/lib/analyze-commit.js:25:9)
    at Array.filter (<anonymous>)
    at module.exports (/home/circleci/project/status-board/node_modules/@semantic-release/commit-analyzer/lib/analyze-commit.js:18:6)
    at filter.every (/home/circleci/project/status-board/node_modules/@semantic-release/commit-analyzer/index.js:48:27)
    at Array.every (<anonymous>)
    at analyzeCommits (/home/circleci/project/status-board/node_modules/@semantic-release/commit-analyzer/index.js:33:5) pluginName: '@semantic-release/commit-analyzer' }npm ERR! code ELIFECYCLE
```

**Comment by pvdlg** [comment]
Are you sure you are using `@semantic-release/commit-analyzer` version `7.0.0-beta.1`? Maybe you have a different version in your lock file.
Can you provide a link to your repo? What is your semantic-release config?

**Comment by jameswlane** [comment]
Here is a link to the repo: https://github.com/jameswlane/status-board

Also here is my [package-lock.json](https://github.com/jameswlane/status-board/blob/master/package-lock.json) and [.realeaserc](https://github.com/jameswlane/status-board/blob/master/.realeaserc)

**Comment by jameswlane** [comment]
Fat fingered the close button 😐

**Comment by pvdlg** [comment]
It seems you are using the version `7.0.0-beta-.2` which contains bugs and has a wrong version format: https://github.com/jameswlane/status-board/blob/362cdb61d672de0d6968541368465845542d4cf7/package-lock.json#L431

This was deprecated a while ago but you still use it because you have a lock file. I'm guessing you should have add a deprecation message when running `npm install`.

**Comment by jameswlane** [comment]
This has been resolved thank you for your help @pvdlg
